[package]

name = "bitburner-scripts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "wasm/lib.rs"

[profile.release]
opt-level = 3

[dependencies]
wasm-bindgen = "0.2.92"
